name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
            dotnet-version: '6.0.x'

      - name: NuGet Restore (.NET Framework)
        run: nuget restore DynamicPermission.sln

      - name: Build (.NET Framework)
        run: msbuild DynamicPermission.sln /p:Configuration=Release
